# Author: SANJAY KR
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/whatsapp_bot
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      JWT_SECRET_KEY: development-secret-key-do-not-use-in-production
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      FLASK_APP: app.main
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      bash -c "
        python scripts/init_db.py &&
        python -m flask run --host=0.0.0.0 --port=8000
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
